spring.application.name=auth-service
server.port=8081

spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}

jwt.secret=${JWT_SECRET}
encryption.secret=${ENCRYPTION_SECRET}

grpc.client.user-service.address=${GRPC_CLIENT_USER_SERVICE_ADDRESS:static://user-service:9090}
grpc.client.user-service.negotiation-type=${GRPC_CLIENT_USER_SERVICE_NEGOTIATION_TYPE:plaintext}

# gRPC Client Security (mTLS)
grpc.client.user-service.security.enabled=${GRPC_CLIENT_USER_SERVICE_SECURITY_ENABLED:false}
grpc.client.user-service.security.client-auth-enabled=true
grpc.client.user-service.security.key-store=${GRPC_CLIENT_USER_SERVICE_SECURITY_KEY_STORE:file:certs/auth-service.jks}
grpc.client.user-service.security.key-store-format=PKCS12
grpc.client.user-service.security.key-store-password=${GRPC_CLIENT_USER_SERVICE_SECURITY_KEY_STORE_PASSWORD:password}
grpc.client.user-service.security.key-password=${GRPC_CLIENT_USER_SERVICE_SECURITY_KEY_PASSWORD:password}
grpc.client.user-service.security.trust-store=${GRPC_CLIENT_USER_SERVICE_SECURITY_TRUST_STORE:file:certs/truststore.jks}
grpc.client.user-service.security.trust-store-format=PKCS12
grpc.client.user-service.security.trust-store-password=${GRPC_CLIENT_USER_SERVICE_SECURITY_TRUST_STORE_PASSWORD:password}
