spring.config.import=optional:classpath:observability-defaults.properties

spring.application.name=content-aggregator-service
server.port=8086

spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:guest}
