spring.config.import=optional:classpath:observability-defaults.properties

spring.application.name=message-service
server.port=8083

grpc.client.user-service.address=${GRPC_CLIENT_USER_SERVICE_ADDRESS:static://user-service:9090}
grpc.client.user-service.negotiation-type=${GRPC_CLIENT_USER_SERVICE_NEGOTIATION_TYPE:plaintext}

# gRPC Client Security (mTLS)
grpc.client.user-service.security.clientAuthEnabled=true
grpc.client.user-service.security.keyStore=${GRPC_CLIENT_USER_SERVICE_SECURITY_KEY_STORE:file:certs/message-service.jks}
grpc.client.user-service.security.keyStoreFormat=PKCS12
grpc.client.user-service.security.keyStorePassword=${GRPC_CLIENT_USER_SERVICE_SECURITY_KEY_STORE_PASSWORD}
grpc.client.user-service.security.privateKeyPassword=${GRPC_CLIENT_USER_SERVICE_SECURITY_KEY_PASSWORD}
grpc.client.user-service.security.trustStore=${GRPC_CLIENT_USER_SERVICE_SECURITY_TRUST_STORE:file:certs/truststore.jks}
grpc.client.user-service.security.trustStoreFormat=PKCS12
grpc.client.user-service.security.trustStorePassword=${GRPC_CLIENT_USER_SERVICE_SECURITY_TRUST_STORE_PASSWORD}

jwt.secret=${JWT_SECRET}
encryption.secret=${ENCRYPTION_SECRET}

spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}

app.test-mode.allowed=false
