spring.application.name=message-service
server.port=8083

grpc.client.user-service.address=${GRPC_CLIENT_USER_SERVICE_ADDRESS:static://user-service:9090}
grpc.client.user-service.negotiation-type=${GRPC_CLIENT_USER_SERVICE_NEGOTIATION_TYPE:plaintext}

# gRPC Client Security (mTLS)
grpc.client.user-service.security.enabled=${GRPC_CLIENT_USER_SERVICE_SECURITY_ENABLED:false}
grpc.client.user-service.security.client-auth-enabled=true
grpc.client.user-service.security.key-store=${GRPC_CLIENT_USER_SERVICE_SECURITY_KEY_STORE:file:certs/message-service.jks}
grpc.client.user-service.security.key-store-format=PKCS12
grpc.client.user-service.security.key-store-password=${GRPC_CLIENT_USER_SERVICE_SECURITY_KEY_STORE_PASSWORD}
grpc.client.user-service.security.key-password=${GRPC_CLIENT_USER_SERVICE_SECURITY_KEY_PASSWORD}
grpc.client.user-service.security.trust-store=${GRPC_CLIENT_USER_SERVICE_SECURITY_TRUST_STORE:file:certs/truststore.jks}
grpc.client.user-service.security.trust-store-format=PKCS12
grpc.client.user-service.security.trust-store-password=${GRPC_CLIENT_USER_SERVICE_SECURITY_TRUST_STORE_PASSWORD}

jwt.secret=${JWT_SECRET}
encryption.secret=${ENCRYPTION_SECRET}
