spring.application.name=message-service
server.port=8083

grpc.client.user-service.address=static://localhost:9090
grpc.client.user-service.negotiation-type=plaintext

jwt.secret=${JWT_SECRET:a-very-long-and-secure-secret-key-that-is-at-least-256-bits}
encryption.secret=${ENCRYPTION_SECRET:another-very-long-and-secure-secret-key-32-chars}
