apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: ai-service
  newTag: latest
- name: auth-service
  newTag: latest
- name: content-aggregator-service
  newTag: latest
- name: feedback-service
  newTag: latest
- name: frontend
  newTag: latest
- name: gateway
  newTag: latest
- name: message-service
  newTag: latest
- name: user-service
  newTag: latest

patches:
- target:
    kind: Deployment
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/imagePullPolicy
      value: Never
