spring.config.import=optional:classpath:observability-defaults.properties

spring.application.name=gateway
server.port=8080

logging.level.org.springframework.cloud.gateway=INFO
logging.level.org.springframework.cloud.gateway.filter.ratelimit=DEBUG
logging.level.reactor.netty.http.client=INFO

services.aggregator=http://localhost:8086
services.feedback=http://localhost:8087
