spring.application.name=ai-service
server.port=8084

spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}

# OpenRouter Configuration
openrouter.api.key=${OPENROUTER_API_KEY}
openrouter.model=${OPENROUTER_MODEL:mistralai/mistral-7b-instruct:free}
openrouter.url=https://openrouter.ai/api/v1/chat/completions

