spring.application.name=user-service
server.port=8082

encryption.secret=${ENCRYPTION_SECRET:another-very-long-and-secure-secret-key-32-chars}
jwt.secret=${JWT_SECRET:a-very-long-and-secure-secret-key-that-is-at-least-256-bits}
