spring.application.name=user-service
server.port=8082

encryption.secret=${ENCRYPTION_SECRET}
jwt.secret=${JWT_SECRET}

# gRPC Server Security (mTLS)
grpc.server.security.enabled=${GRPC_SERVER_SECURITY_ENABLED:false}
grpc.server.security.key-store=${GRPC_SERVER_SECURITY_KEY_STORE:file:certs/user-service.jks}
grpc.server.security.key-store-type=PKCS12
grpc.server.security.key-store-password=${GRPC_SERVER_SECURITY_KEY_STORE_PASSWORD:password}
grpc.server.security.key-password=${GRPC_SERVER_SECURITY_KEY_PASSWORD:password}
grpc.server.security.trust-store=${GRPC_SERVER_SECURITY_TRUST_STORE:file:certs/truststore.jks}
grpc.server.security.trust-store-type=PKCS12
grpc.server.security.trust-store-password=${GRPC_SERVER_SECURITY_TRUST_STORE_PASSWORD:password}
grpc.server.security.client-auth=${GRPC_SERVER_SECURITY_CLIENT_AUTH:REQUIRE}

spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}

spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
