spring.config.import=optional:classpath:observability-defaults.properties

spring.application.name=user-service
server.port=8082

# gRPC Server Security (mTLS)
grpc.server.security.enabled=${GRPC_SERVER_SECURITY_ENABLED:true}
grpc.server.security.key-store=${GRPC_SERVER_SECURITY_KEY_STORE:file:certs/user-service.jks}
grpc.server.security.key-store-type=JKS
grpc.server.security.key-store-password=${GRPC_SERVER_SECURITY_KEY_STORE_PASSWORD}
grpc.server.security.key-password=${GRPC_SERVER_SECURITY_KEY_PASSWORD}
grpc.server.security.trust-store=${GRPC_SERVER_SECURITY_TRUST_STORE:file:certs/truststore.jks}
grpc.server.security.trust-store-type=JKS
grpc.server.security.trust-store-password=${GRPC_SERVER_SECURITY_TRUST_STORE_PASSWORD}
grpc.server.security.client-auth=${GRPC_SERVER_SECURITY_CLIENT_AUTH:REQUIRE}

spring.rabbitmq.listener.simple.default-requeue-rejected=false

# Admin Setup
admin.setup.username=${ADMIN_SETUP_USERNAME:admin}
admin.setup.password=${ADMIN_SETUP_PASSWORD:admin-password-2026}
admin.setup.email=${ADMIN_SETUP_EMAIL:admin@adaptachat.io}
