apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-service
  template:
    metadata:
      labels:
        app: message-service
    spec:
      containers:
      - name: message-service
        image: message-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8083
        resources:
          requests:
            cpu: "100m"
            memory: "384Mi"
          limits:
            cpu: "300m"
            memory: "768Mi"
        env:
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: adapta-secrets
              key: jwt-secret
        - name: ENCRYPTION_SECRET
          valueFrom:
            secretKeyRef:
              name: adapta-secrets
              key: encryption-secret
        - name: SPRING_DATA_MONGODB_URI
          value: mongodb://mongodb:27017/messagedb
        - name: SPRING_RABBITMQ_HOST
          value: rabbitmq
        - name: GRPC_CLIENT_USER_SERVICE_ADDRESS
          value: static://user-service:9090
---
apiVersion: v1
kind: Service
metadata:
  name: message-service
spec:
  selector:
    app: message-service
  ports:
  - port: 8080
    targetPort: 8083
