spring.config.import=optional:classpath:observability-defaults.properties

spring.application.name=feedback-service
server.port=8087
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/feedbackdb}
