spring.application.name=feedback-service
server.port=8080
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://mongodb:27017/feedbackdb}
jwt.secret=${JWT_SECRET}
encryption.secret=${ENCRYPTION_SECRET}
