apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ai-service.yaml
- auth-service.yaml
- content-aggregator-service.yaml
- feedback-service.yaml
- frontend.yaml
- gateway.yaml
- message-service.yaml
- user-service.yaml
